services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "30601:80" 
    depends_on:
      - frontend
      - backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NEXT_PUBLIC_API_URL=http://localhost:5001
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "5001"
    volumes:
      # - ./backend:/app
      # - /app/node_modules
      - fileseedshare_shared_data:/app/uploads
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/fileseedshare
    depends_on:
      - db

  cleaner:
    build:
      context: ./cleaner
      dockerfile: Dockerfile
    environment:
      DB_NAME: fileseedshare
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    volumes:
      - fileseedshare_shared_data:/app/uploads
      - ./log:/var/log


  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: postgres_db
    expose:
      - "5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fileseedshare
    volumes:
      - fileseedshare_db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  fileseedshare_db_data:
  fileseedshare_shared_data:
